name: Build & deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Installing Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: Accessing the root folder 
        run: cd validator-ui

      - name: Installing NPM packages
        run: npm i
        working-directory: validator-ui  # Setarea directorului de lucru aici

      - name: Building project
        run: npm run build
        working-directory: validator-ui  # Setarea directorului de lucru aici

      - name: Uploading production-ready build files
        uses: actions/upload-artifact@v2
        with:
          name: production-files
          path: ./validator-ui/build  # Corectarea căii către directorul de construcție

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Downloading artifact
        uses: actions/download-artifact@v2
        with:
          name: production-files
          path: ./validator-ui/build  # Corectarea căii către directorul de construcție

      - name: Deploying to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./validator-ui/build  # Corectarea căii către directorul de construcție
